### ISSUE TITLE
Console error on login preventing app publish

### ISSUE THREAD

**Issue by LeGaryGary** [cedriking/ArweaveApps#6]
TypeError: Cannot read property 'html' of null
    at n.<anonymous> (app.8825e9a6.js:107)
    at app.8825e9a6.js:107
    at Object.next (app.8825e9a6.js:107)
    at r (app.8825e9a6.js:107)

This error prevents people from publishing their apps

**Comment by cedriking** [comment]
This issue has been solved a few version back, forgot to close this issue >.<
